### ISSUE TITLE
Rendering fails when Flutter ^v3.22.0, RELEASE mode, and iOS/Android target

### ISSUE THREAD

**Issue by kNoAPP** [huhuang03/reorderable_grid_view#82]
Starting with v3.22.0 and only occurring in release mode, this library fails to render a `ReorderableGridView.count()` instead throwing an exception:
```
Null check operator used on a null value
I/flutter ( 2283): #0      ReorderableItemView.wrapMeList (package:reorderable_grid_view/src/reorderable_item.dart:39)
I/flutter ( 2283): #1      new ReorderableGridView.count (package:reorderable_grid_view/reorderable_grid_view.dart:245)
```

The result is a grey screen.

For some reason, debug mode and web are not impacted. And this bug DOES NOT appear in Flutter v3.19.6.

**Comment by kNoAPP** [comment]
I'm just dumb oops. I was failing this precondition on my side:

```
      assert(() {
        if (child.key == null) {
          throw FlutterError(
            'Every item of ReorderableGridView must have a key.',
          );
        }
        return true;
      }());
```

For some reason, the library continues to work despite that failure (until now). Props I guess?

Thank you, closing this issue.
